include Makefile.sources

TARGET_NAME = gearlynx-tests
COMLYNX_TARGET_NAME = gearlynx-comlynx-tests
COMLYNX_WIRE_TARGET_NAME = gearlynx-comlynx-wire-tests
UART_TURBO_TARGET_NAME = gearlynx-uart-turbo-tests
GIT_VERSION := $(shell git describe --abbrev=7 --dirty --always --tags)
UNAME_S := $(shell uname -s)
PLATFORM = "undefined"

OBJECTS += $(SOURCES_C:.c=.o) $(SOURCES_CXX:.cpp=.o)

INCLUDES += -I$(SRC_DIR)
INCLUDES += -I$(DEPS_DIR)/miniz

USE_CLANG ?= 0
ifeq ($(USE_CLANG), 1)
    CXX = clang++
    CC = clang
else
    CXX = g++
    CC = gcc
endif

CPPFLAGS += $(INCLUDES)
CPPFLAGS += -Wall -Wextra -Wformat -fno-exceptions -DGLYNX_TESTING=1 -DGLYNX_DISABLE_DISASSEMBLER=1 -DEMULATOR_BUILD=\"$(GIT_VERSION)\"
CXXFLAGS += -std=c++11
CFLAGS += -std=c99

$(DEPS_DIR)/%.o: CPPFLAGS += -w

DEBUG ?= 0
ifeq ($(DEBUG), 1)
    CPPFLAGS +=-DDEBUG -g3
else
    CPPFLAGS +=-DNDEBUG -O3 -flto=auto
    LDFLAGS += -O3 -flto=auto
endif

SANITIZE ?= 0
ifeq ($(SANITIZE), 1)
    CPPFLAGS +=-fsanitize=address
    LDFLAGS += -lasan
endif

ifeq ($(UNAME_S), Linux) #LINUX
    PLATFORM = "Linux"
    TARGET := $(TARGET_NAME)
else ifeq ($(UNAME_S), Darwin) #APPLE
    PLATFORM = "macOS"
    LDFLAGS += -L/usr/local/lib
    CPPFLAGS += -I/usr/local/include -I/opt/local/include
    TARGET := $(TARGET_NAME)
else
    PLATFORM = "Generic Unix-like/BSD"
    CXXFLAGS += -std=gnu++11
    TARGET := $(TARGET_NAME)
endif

all: $(TARGET)
	@echo Build complete for $(PLATFORM)

comlynx: $(COMLYNX_TARGET_NAME)
	@echo ComLynx tests build complete for $(PLATFORM)

comlynx-wire: $(COMLYNX_WIRE_TARGET_NAME)
	@echo ComLynx wire tests build complete for $(PLATFORM)

uart-turbo: $(UART_TURBO_TARGET_NAME)
	@echo UART turbo tests build complete for $(PLATFORM)

$(UART_TURBO_TARGET_NAME): uart_turbo_tests.cpp $(filter-out ./main.o,$(OBJECTS))
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

$(COMLYNX_WIRE_TARGET_NAME): comlynx_wire_tests.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -I../platforms/shared/desktop -o $@ $^ $(LDFLAGS)

$(COMLYNX_TARGET_NAME): comlynx_tests.cpp ../platforms/shared/desktop/comlynx/comlynx_manager.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -I../platforms/shared/desktop -pthread -o $@ $^ $(LDFLAGS)

$(TARGET): $(OBJECTS)
	$(CXX) -o $@ $(OBJECTS) $(LDFLAGS)

%.o: %.mm
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $<

%.o: %.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $<

%.o: %.c
	$(CC) $(CPPFLAGS) $(CFLAGS) -c -o $@ $<

clean:
	rm -f $(OBJECTS) $(TARGET) $(COMLYNX_TARGET_NAME) $(COMLYNX_WIRE_TARGET_NAME) $(UART_TURBO_TARGET_NAME)
