/*
 * Gearlynx - Lynx Emulator
 * Copyright (C) 2025  Ignacio Sanchez

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/
 *
 */

#ifndef M6502_NAME_H
#define M6502_NAME_H

enum GLYNX_OPCode_Type
{
    GLYNX_OPCode_Type_Implied,
    GLYNX_OPCode_Type_1b,
    GLYNX_OPCode_Type_1b_1b,
    GLYNX_OPCode_Type_1b_2b,
    GLYNX_OPCode_Type_2b,
    GLYNX_OPCode_Type_2b_2b_2b,
    GLYNX_OPCode_Type_1b_Relative,
    GLYNX_OPCode_Type_1b_1b_Relative,
    GLYNX_OPCode_Type_BRK,
    GLYNX_OPCode_Type_Data,
};

struct GLYNX_OPCode_Info
{
    const char* name[GLYNX_Disassembler_Syntax_Count];
    GLYNX_OPCode_Type type;
};

#define GLYNX_OPCODE(name, type) { { name, name, name, name }, type }
#define GLYNX_OPCODE_SYNTAX(gearlynx, cc65, lyxass, mads, type) { { gearlynx, cc65, lyxass, mads }, type }

static const GLYNX_OPCode_Info k_m6502_opcode_names[256] = {
    GLYNX_OPCODE_SYNTAX("{n}BRK", "{n}BRK {o}#$%02X", "{n}BRK {o}#$%02X", "{n}BRK", GLYNX_OPCode_Type_BRK),
    GLYNX_OPCODE_SYNTAX("{n}ORA {o}$(%02X,X)", "{n}ORA {o}($%02X,X)", "{n}ORA {o}($%02X,X)", "{n}ORA {o}($%02X,X)", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$02", "{n}.db {o}$02", "{n}dta {o}$02", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$03", "{n}.db {o}$03", "{n}dta {o}$03", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}TSB {o}$%02X", "{n}TSB {o}<$%02X", "{n}TSB {o}<$%02X", "{n}TSB {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}ORA {o}$%02X", "{n}ORA {o}<$%02X", "{n}ORA {o}<$%02X", "{n}ORA {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}ASL {o}$%02X", "{n}ASL {o}<$%02X", "{n}ASL {o}<$%02X", "{n}ASL {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}RMB {o}0,$%02X", "{n}RMB0 {o}$%02X", "{n}RMB0 {o}$%02X", "{n}dta {o}$07,$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}PHP", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE("{n}ORA {o}#$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}ASL {o}A", "{n}ASL {o}A", "{n}ASL", "{n}ASL", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$0B", "{n}.db {o}$0B", "{n}dta {o}$0B", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE("{n}TSB {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}ORA {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}ASL {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE_SYNTAX("{n}BBR {o}0,$%02X,$%04X  {e}[%+d]", "{n}BBR0 {o}$%02X,*%+d", "{n}BBR0 {o}$%02X,*%+d", "{n}dta {o}$0F,$%02X,$%02X", GLYNX_OPCode_Type_1b_1b_Relative),

    GLYNX_OPCODE_SYNTAX("{n}BPL {o}$%04X  {e}[%+d]", "{n}BPL {o}*%+d", "{n}BPL {o}*%+d", "{n}BPL {o}*%+d", GLYNX_OPCode_Type_1b_Relative),
    GLYNX_OPCODE("{n}ORA {o}($%02X),Y", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}ORA {o}($%02X)", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$13", "{n}.db {o}$13", "{n}dta {o}$13", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}TRB {o}$%02X", "{n}TRB {o}<$%02X", "{n}TRB {o}<$%02X", "{n}TRB {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}ORA {o}$%02X,X", "{n}ORA {o}<$%02X,X", "{n}ORA {o}<$%02X,X", "{n}ORA {o}$%02X,X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}ASL {o}$%02X,X", "{n}ASL {o}<$%02X,X", "{n}ASL {o}<$%02X,X", "{n}ASL {o}$%02X,X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}RMB {o}1,$%02X", "{n}RMB1 {o}$%02X", "{n}RMB1 {o}$%02X", "{n}dta {o}$17,$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}CLC", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE("{n}ORA {o}$%04X,Y", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE_SYNTAX("{n}INC {o}A", "{n}INC {o}A", "{n}INA", "{n}INA", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$1B", "{n}.db {o}$1B", "{n}dta {o}$1B", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE("{n}TRB {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}ORA {o}$%04X,X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}ASL {o}$%04X,X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE_SYNTAX("{n}BBR {o}1,$%02X,$%04X  {e}[%+d]", "{n}BBR1 {o}$%02X,*%+d", "{n}BBR1 {o}$%02X,*%+d", "{n}dta {o}$1F,$%02X,$%02X", GLYNX_OPCode_Type_1b_1b_Relative),

    GLYNX_OPCODE("{n}JSR {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE_SYNTAX("{n}AND {o}$(%02X,X)", "{n}AND {o}($%02X,X)", "{n}AND {o}($%02X,X)", "{n}AND {o}($%02X,X)", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$22", "{n}.db {o}$22", "{n}dta {o}$22", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$23", "{n}.db {o}$23", "{n}dta {o}$23", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}BIT {o}$%02X", "{n}BIT {o}<$%02X", "{n}BIT {o}<$%02X", "{n}BIT {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}AND {o}$%02X", "{n}AND {o}<$%02X", "{n}AND {o}<$%02X", "{n}AND {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}ROL {o}$%02X", "{n}ROL {o}<$%02X", "{n}ROL {o}<$%02X", "{n}ROL {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}RMB {o}2,$%02X", "{n}RMB2 {o}$%02X", "{n}RMB2 {o}$%02X", "{n}dta {o}$27,$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}PLP", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE("{n}AND {o}#$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}ROL {o}A", "{n}ROL {o}A", "{n}ROL", "{n}ROL", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$2B", "{n}.db {o}$2B", "{n}dta {o}$2B", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE("{n}BIT {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}AND {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}ROL {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE_SYNTAX("{n}BBR {o}2,$%02X,$%04X  {e}[%+d]", "{n}BBR2 {o}$%02X,*%+d", "{n}BBR2 {o}$%02X,*%+d", "{n}dta {o}$2F,$%02X,$%02X", GLYNX_OPCode_Type_1b_1b_Relative),

    GLYNX_OPCODE_SYNTAX("{n}BMI {o}$%04X  {e}[%+d]", "{n}BMI {o}*%+d", "{n}BMI {o}*%+d", "{n}BMI {o}*%+d", GLYNX_OPCode_Type_1b_Relative),
    GLYNX_OPCODE("{n}AND {o}($%02X),Y", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}AND {o}($%02X)", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$33", "{n}.db {o}$33", "{n}dta {o}$33", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}BIT {o}$%02X,X", "{n}BIT {o}<$%02X,X", "{n}BIT {o}<$%02X,X", "{n}BIT {o}$%02X,X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}AND {o}$%02X,X", "{n}AND {o}<$%02X,X", "{n}AND {o}<$%02X,X", "{n}AND {o}$%02X,X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}ROL {o}$%02X,X", "{n}ROL {o}<$%02X,X", "{n}ROL {o}<$%02X,X", "{n}ROL {o}$%02X,X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}RMB {o}3,$%02X", "{n}RMB3 {o}$%02X", "{n}RMB3 {o}$%02X", "{n}dta {o}$37,$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}SEC", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE("{n}AND {o}$%04X,Y", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE_SYNTAX("{n}DEC {o}A", "{n}DEC {o}A", "{n}DEA", "{n}DEA", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$3B", "{n}.db {o}$3B", "{n}dta {o}$3B", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE("{n}BIT {o}$%04X,X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}AND {o}$%04X,X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}ROL {o}$%04X,X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE_SYNTAX("{n}BBR {o}3,$%02X,$%04X  {e}[%+d]", "{n}BBR3 {o}$%02X,*%+d", "{n}BBR3 {o}$%02X,*%+d", "{n}dta {o}$3F,$%02X,$%02X", GLYNX_OPCode_Type_1b_1b_Relative),

    GLYNX_OPCODE("{n}RTI", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE_SYNTAX("{n}EOR {o}$(%02X,X)", "{n}EOR {o}($%02X,X)", "{n}EOR {o}($%02X,X)", "{n}EOR {o}($%02X,X)", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$42", "{n}.db {o}$42", "{n}dta {o}$42", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$43", "{n}.db {o}$43", "{n}dta {o}$43", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$44", "{n}.db {o}$44", "{n}dta {o}$44", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}EOR {o}$%02X", "{n}EOR {o}<$%02X", "{n}EOR {o}<$%02X", "{n}EOR {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}LSR {o}$%02X", "{n}LSR {o}<$%02X", "{n}LSR {o}<$%02X", "{n}LSR {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}RMB {o}4,$%02X", "{n}RMB4 {o}$%02X", "{n}RMB4 {o}$%02X", "{n}dta {o}$47,$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}PHA", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE("{n}EOR {o}#$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}LSR {o}A", "{n}LSR {o}A", "{n}LSR", "{n}LSR", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$4B", "{n}.db {o}$4B", "{n}dta {o}$4B", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE("{n}JMP {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}EOR {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}LSR {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE_SYNTAX("{n}BBR {o}4,$%02X,$%04X  {e}[%+d]", "{n}BBR4 {o}$%02X,*%+d", "{n}BBR4 {o}$%02X,*%+d", "{n}dta {o}$4F,$%02X,$%02X", GLYNX_OPCode_Type_1b_1b_Relative),

    GLYNX_OPCODE_SYNTAX("{n}BVC {o}$%04X  {e}[%+d]", "{n}BVC {o}*%+d", "{n}BVC {o}*%+d", "{n}BVC {o}*%+d", GLYNX_OPCode_Type_1b_Relative),
    GLYNX_OPCODE("{n}EOR {o}($%02X),Y", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}EOR {o}($%02X)", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$53", "{n}.db {o}$53", "{n}dta {o}$53", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$54", "{n}.db {o}$54", "{n}dta {o}$54", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}EOR {o}$%02X,X", "{n}EOR {o}<$%02X,X", "{n}EOR {o}<$%02X,X", "{n}EOR {o}$%02X,X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}LSR {o}$%02X,X", "{n}LSR {o}<$%02X,X", "{n}LSR {o}<$%02X,X", "{n}LSR {o}$%02X,X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}RMB {o}5,$%02X", "{n}RMB5 {o}$%02X", "{n}RMB5 {o}$%02X", "{n}dta {o}$57,$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}CLI", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE("{n}EOR {o}$%04X,Y", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}PHY", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$5B", "{n}.db {o}$5B", "{n}dta {o}$5B", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$5C", "{n}.db {o}$5C", "{n}dta {o}$5C", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE("{n}EOR {o}$%04X,X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}LSR {o}$%04X,X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE_SYNTAX("{n}BBR {o}5,$%02X,$%04X  {e}[%+d]", "{n}BBR5 {o}$%02X,*%+d", "{n}BBR5 {o}$%02X,*%+d", "{n}dta {o}$5F,$%02X,$%02X", GLYNX_OPCode_Type_1b_1b_Relative),

    GLYNX_OPCODE("{n}RTS", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE_SYNTAX("{n}ADC {o}$(%02X,X)", "{n}ADC {o}($%02X,X)", "{n}ADC {o}($%02X,X)", "{n}ADC {o}($%02X,X)", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$62", "{n}.db {o}$62", "{n}dta {o}$62", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$63", "{n}.db {o}$63", "{n}dta {o}$63", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}STZ {o}$%02X", "{n}STZ {o}<$%02X", "{n}STZ {o}<$%02X", "{n}STZ {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}ADC {o}$%02X", "{n}ADC {o}<$%02X", "{n}ADC {o}<$%02X", "{n}ADC {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}ROR {o}$%02X", "{n}ROR {o}<$%02X", "{n}ROR {o}<$%02X", "{n}ROR {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}RMB {o}6,$%02X", "{n}RMB6 {o}$%02X", "{n}RMB6 {o}$%02X", "{n}dta {o}$67,$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}PLA", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE("{n}ADC {o}#$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}ROR {o}A", "{n}ROR {o}A", "{n}ROR", "{n}ROR", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$6B", "{n}.db {o}$6B", "{n}dta {o}$6B", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE("{n}JMP {o}($%04X)", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}ADC {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}ROR {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE_SYNTAX("{n}BBR {o}6,$%02X,$%04X  {e}[%+d]", "{n}BBR6 {o}$%02X,*%+d", "{n}BBR6 {o}$%02X,*%+d", "{n}dta {o}$6F,$%02X,$%02X", GLYNX_OPCode_Type_1b_1b_Relative),

    GLYNX_OPCODE_SYNTAX("{n}BVS {o}$%04X  {e}[%+d]", "{n}BVS {o}*%+d", "{n}BVS {o}*%+d", "{n}BVS {o}*%+d", GLYNX_OPCode_Type_1b_Relative),
    GLYNX_OPCODE("{n}ADC {o}($%02X),Y", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}ADC {o}($%02X)", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$73", "{n}.db {o}$73", "{n}dta {o}$73", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}STZ {o}$%02X,X", "{n}STZ {o}<$%02X,X", "{n}STZ {o}<$%02X,X", "{n}STZ {o}$%02X,X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}ADC {o}$%02X,X", "{n}ADC {o}<$%02X,X", "{n}ADC {o}<$%02X,X", "{n}ADC {o}$%02X,X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}ROR {o}$%02X,X", "{n}ROR {o}<$%02X,X", "{n}ROR {o}<$%02X,X", "{n}ROR {o}$%02X,X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}RMB {o}7,$%02X", "{n}RMB7 {o}$%02X", "{n}RMB7 {o}$%02X", "{n}dta {o}$77,$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}SEI", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE("{n}ADC {o}$%04X,Y", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}PLY", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$7B", "{n}.db {o}$7B", "{n}dta {o}$7B", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}JMP {o}$(%04X,X)", "{n}JMP {o}($%04X,X)", "{n}JMP {o}($%04X,X)", "{n}JMP {o}($%04X,X)", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}ADC {o}$%04X,X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}ROR {o}$%04X,X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE_SYNTAX("{n}BBR {o}7,$%02X,$%04X  {e}[%+d]", "{n}BBR7 {o}$%02X,*%+d", "{n}BBR7 {o}$%02X,*%+d", "{n}dta {o}$7F,$%02X,$%02X", GLYNX_OPCode_Type_1b_1b_Relative),

    GLYNX_OPCODE_SYNTAX("{n}BRA {o}$%04X  {e}[%+d]", "{n}BRA {o}*%+d", "{n}BRA {o}*%+d", "{n}BRA {o}*%+d", GLYNX_OPCode_Type_1b_Relative),
    GLYNX_OPCODE_SYNTAX("{n}STA {o}$(%02X,X)", "{n}STA {o}($%02X,X)", "{n}STA {o}($%02X,X)", "{n}STA {o}($%02X,X)", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$82", "{n}.db {o}$82", "{n}dta {o}$82", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$83", "{n}.db {o}$83", "{n}dta {o}$83", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}STY {o}$%02X", "{n}STY {o}<$%02X", "{n}STY {o}<$%02X", "{n}STY {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}STA {o}$%02X", "{n}STA {o}<$%02X", "{n}STA {o}<$%02X", "{n}STA {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}STX {o}$%02X", "{n}STX {o}<$%02X", "{n}STX {o}<$%02X", "{n}STX {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}SMB {o}0,$%02X", "{n}SMB0 {o}$%02X", "{n}SMB0 {o}$%02X", "{n}dta {o}$87,$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}DEY", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE("{n}BIT {o}#$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}TXA", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$8B", "{n}.db {o}$8B", "{n}dta {o}$8B", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE("{n}STY {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}STA {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}STX {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE_SYNTAX("{n}BBS {o}0,$%02X,$%04X  {e}[%+d]", "{n}BBS0 {o}$%02X,*%+d", "{n}BBS0 {o}$%02X,*%+d", "{n}dta {o}$8F,$%02X,$%02X", GLYNX_OPCode_Type_1b_1b_Relative),

    GLYNX_OPCODE_SYNTAX("{n}BCC {o}$%04X  {e}[%+d]", "{n}BCC {o}*%+d", "{n}BCC {o}*%+d", "{n}BCC {o}*%+d", GLYNX_OPCode_Type_1b_Relative),
    GLYNX_OPCODE("{n}STA {o}($%02X),Y", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}STA {o}($%02X)", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$93", "{n}.db {o}$93", "{n}dta {o}$93", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}STY {o}$%02X,X", "{n}STY {o}<$%02X,X", "{n}STY {o}<$%02X,X", "{n}STY {o}$%02X,X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}STA {o}$%02X,X", "{n}STA {o}<$%02X,X", "{n}STA {o}<$%02X,X", "{n}STA {o}$%02X,X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}STX {o}$%02X,Y", "{n}STX {o}<$%02X,Y", "{n}STX {o}<$%02X,Y", "{n}STX {o}$%02X,Y", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}SMB {o}1,$%02X", "{n}SMB1 {o}$%02X", "{n}SMB1 {o}$%02X", "{n}dta {o}$97,$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}TYA", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE("{n}STA {o}$%04X,Y", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}TXS", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$9B", "{n}.db {o}$9B", "{n}dta {o}$9B", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE("{n}STZ {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}STA {o}$%04X,X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}STZ {o}$%04X,X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE_SYNTAX("{n}BBS {o}1,$%02X,$%04X  {e}[%+d]", "{n}BBS1 {o}$%02X,*%+d", "{n}BBS1 {o}$%02X,*%+d", "{n}dta {o}$9F,$%02X,$%02X", GLYNX_OPCode_Type_1b_1b_Relative),

    GLYNX_OPCODE("{n}LDY {o}#$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}LDA {o}$(%02X,X)", "{n}LDA {o}($%02X,X)", "{n}LDA {o}($%02X,X)", "{n}LDA {o}($%02X,X)", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}LDX {o}#$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$A3", "{n}.db {o}$A3", "{n}dta {o}$A3", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}LDY {o}$%02X", "{n}LDY {o}<$%02X", "{n}LDY {o}<$%02X", "{n}LDY {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}LDA {o}$%02X", "{n}LDA {o}<$%02X", "{n}LDA {o}<$%02X", "{n}LDA {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}LDX {o}$%02X", "{n}LDX {o}<$%02X", "{n}LDX {o}<$%02X", "{n}LDX {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}SMB {o}2,$%02X", "{n}SMB2 {o}$%02X", "{n}SMB2 {o}$%02X", "{n}dta {o}$A7,$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}TAY", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE("{n}LDA {o}#$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}TAX", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$AB", "{n}.db {o}$AB", "{n}dta {o}$AB", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE("{n}LDY {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}LDA {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}LDX {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE_SYNTAX("{n}BBS {o}2,$%02X,$%04X  {e}[%+d]", "{n}BBS2 {o}$%02X,*%+d", "{n}BBS2 {o}$%02X,*%+d", "{n}dta {o}$AF,$%02X,$%02X", GLYNX_OPCode_Type_1b_1b_Relative),

    GLYNX_OPCODE_SYNTAX("{n}BCS {o}$%04X  {e}[%+d]", "{n}BCS {o}*%+d", "{n}BCS {o}*%+d", "{n}BCS {o}*%+d", GLYNX_OPCode_Type_1b_Relative),
    GLYNX_OPCODE("{n}LDA {o}($%02X),Y", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}LDA {o}($%02X)", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$B3", "{n}.db {o}$B3", "{n}dta {o}$B3", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}LDY {o}$%02X,X", "{n}LDY {o}<$%02X,X", "{n}LDY {o}<$%02X,X", "{n}LDY {o}$%02X,X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}LDA {o}$%02X,X", "{n}LDA {o}<$%02X,X", "{n}LDA {o}<$%02X,X", "{n}LDA {o}$%02X,X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}LDX {o}$%02X,Y", "{n}LDX {o}<$%02X,Y", "{n}LDX {o}<$%02X,Y", "{n}LDX {o}$%02X,Y", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}SMB {o}3,$%02X", "{n}SMB3 {o}$%02X", "{n}SMB3 {o}$%02X", "{n}dta {o}$B7,$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}CLV", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE("{n}LDA {o}$%04X,Y", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}TSX", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$BB", "{n}.db {o}$BB", "{n}dta {o}$BB", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE("{n}LDY {o}$%04X,X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}LDA {o}$%04X,X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}LDX {o}$%04X,Y", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE_SYNTAX("{n}BBS {o}3,$%02X,$%04X  {e}[%+d]", "{n}BBS3 {o}$%02X,*%+d", "{n}BBS3 {o}$%02X,*%+d", "{n}dta {o}$BF,$%02X,$%02X", GLYNX_OPCode_Type_1b_1b_Relative),

    GLYNX_OPCODE("{n}CPY {o}#$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}CMP {o}$(%02X,X)", "{n}CMP {o}($%02X,X)", "{n}CMP {o}($%02X,X)", "{n}CMP {o}($%02X,X)", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$C2", "{n}.db {o}$C2", "{n}dta {o}$C2", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$C3", "{n}.db {o}$C3", "{n}dta {o}$C3", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}CPY {o}$%02X", "{n}CPY {o}<$%02X", "{n}CPY {o}<$%02X", "{n}CPY {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}CMP {o}$%02X", "{n}CMP {o}<$%02X", "{n}CMP {o}<$%02X", "{n}CMP {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}DEC {o}$%02X", "{n}DEC {o}<$%02X", "{n}DEC {o}<$%02X", "{n}DEC {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}SMB {o}4,$%02X", "{n}SMB4 {o}$%02X", "{n}SMB4 {o}$%02X", "{n}dta {o}$C7,$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}INY", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE("{n}CMP {o}#$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}DEX", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$CB", "{n}.db {o}$CB", "{n}dta {o}$CB", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE("{n}CPY {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}CMP {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}DEC {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE_SYNTAX("{n}BBS {o}4,$%02X,$%04X  {e}[%+d]", "{n}BBS4 {o}$%02X,*%+d", "{n}BBS4 {o}$%02X,*%+d", "{n}dta {o}$CF,$%02X,$%02X", GLYNX_OPCode_Type_1b_1b_Relative),

    GLYNX_OPCODE_SYNTAX("{n}BNE {o}$%04X  {e}[%+d]", "{n}BNE {o}*%+d", "{n}BNE {o}*%+d", "{n}BNE {o}*%+d", GLYNX_OPCode_Type_1b_Relative),
    GLYNX_OPCODE("{n}CMP {o}($%02X),Y", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}CMP {o}($%02X)", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$D3", "{n}.db {o}$D3", "{n}dta {o}$D3", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$D4", "{n}.db {o}$D4", "{n}dta {o}$D4", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}CMP {o}$%02X,X", "{n}CMP {o}<$%02X,X", "{n}CMP {o}<$%02X,X", "{n}CMP {o}$%02X,X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}DEC {o}$%02X,X", "{n}DEC {o}<$%02X,X", "{n}DEC {o}<$%02X,X", "{n}DEC {o}$%02X,X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}SMB {o}5,$%02X", "{n}SMB5 {o}$%02X", "{n}SMB5 {o}$%02X", "{n}dta {o}$D7,$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}CLD", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE("{n}CMP {o}$%04X,Y", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}PHX", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$DB", "{n}.db {o}$DB", "{n}dta {o}$DB", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$DC", "{n}.db {o}$DC", "{n}dta {o}$DC", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE("{n}CMP {o}$%04X,X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}DEC {o}$%04X,X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE_SYNTAX("{n}BBS {o}5,$%02X,$%04X  {e}[%+d]", "{n}BBS5 {o}$%02X,*%+d", "{n}BBS5 {o}$%02X,*%+d", "{n}dta {o}$DF,$%02X,$%02X", GLYNX_OPCode_Type_1b_1b_Relative),

    GLYNX_OPCODE("{n}CPX {o}#$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}SBC {o}$(%02X,X)", "{n}SBC {o}($%02X,X)", "{n}SBC {o}($%02X,X)", "{n}SBC {o}($%02X,X)", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$E2", "{n}.db {o}$E2", "{n}dta {o}$E2", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$E3", "{n}.db {o}$E3", "{n}dta {o}$E3", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}CPX {o}$%02X", "{n}CPX {o}<$%02X", "{n}CPX {o}<$%02X", "{n}CPX {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}SBC {o}$%02X", "{n}SBC {o}<$%02X", "{n}SBC {o}<$%02X", "{n}SBC {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}INC {o}$%02X", "{n}INC {o}<$%02X", "{n}INC {o}<$%02X", "{n}INC {o}$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}SMB {o}6,$%02X", "{n}SMB6 {o}$%02X", "{n}SMB6 {o}$%02X", "{n}dta {o}$E7,$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}INX", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE("{n}SBC {o}#$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}NOP", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$EB", "{n}.db {o}$EB", "{n}dta {o}$EB", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE("{n}CPX {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}SBC {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}INC {o}$%04X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE_SYNTAX("{n}BBS {o}6,$%02X,$%04X  {e}[%+d]", "{n}BBS6 {o}$%02X,*%+d", "{n}BBS6 {o}$%02X,*%+d", "{n}dta {o}$EF,$%02X,$%02X", GLYNX_OPCode_Type_1b_1b_Relative),

    GLYNX_OPCODE_SYNTAX("{n}BEQ {o}$%04X  {e}[%+d]", "{n}BEQ {o}*%+d", "{n}BEQ {o}*%+d", "{n}BEQ {o}*%+d", GLYNX_OPCode_Type_1b_Relative),
    GLYNX_OPCODE("{n}SBC {o}($%02X),Y", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}SBC {o}($%02X)", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$F3", "{n}.db {o}$F3", "{n}dta {o}$F3", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$F4", "{n}.db {o}$F4", "{n}dta {o}$F4", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}SBC {o}$%02X,X", "{n}SBC {o}<$%02X,X", "{n}SBC {o}<$%02X,X", "{n}SBC {o}$%02X,X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}INC {o}$%02X,X", "{n}INC {o}<$%02X,X", "{n}INC {o}<$%02X,X", "{n}INC {o}$%02X,X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE_SYNTAX("{n}SMB {o}7,$%02X", "{n}SMB7 {o}$%02X", "{n}SMB7 {o}$%02X", "{n}dta {o}$F7,$%02X", GLYNX_OPCode_Type_1b),
    GLYNX_OPCODE("{n}SED", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE("{n}SBC {o}$%04X,Y", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}PLX", GLYNX_OPCode_Type_Implied),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$FB", "{n}.db {o}$FB", "{n}dta {o}$FB", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE_SYNTAX("{n}NOP  {e}[UNOFFICIAL]", "{n}.byte {o}$FC", "{n}.db {o}$FC", "{n}dta {o}$FC", GLYNX_OPCode_Type_Data),
    GLYNX_OPCODE("{n}SBC {o}$%04X,X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE("{n}INC {o}$%04X,X", GLYNX_OPCode_Type_2b),
    GLYNX_OPCODE_SYNTAX("{n}BBS {o}7,$%02X,$%04X  {e}[%+d]", "{n}BBS7 {o}$%02X,*%+d", "{n}BBS7 {o}$%02X,*%+d", "{n}dta {o}$FF,$%02X,$%02X", GLYNX_OPCode_Type_1b_1b_Relative)
};

#undef GLYNX_OPCODE_SYNTAX
#undef GLYNX_OPCODE

#endif /* M6502_NAME_H */
